export const GET_MISSION = "CAD_LITE_GET_MISSION";
export const GET_MISSION_SUCCESS = "CAD_LITE_GET_MISSION_SUCCESS";
export const GET_MISSION_FAILED = "CAD_LITE_GET_MISSION_FAILED";

export const GET_MISSION_BY_ID = "CAD_LITE_GET_MISSION_BY_ID";
export const GET_MISSION_BY_ID_SUCCESS = "CAD_LITE_GET_MISSION_BY_ID_SUCCESS";
export const GET_MISSION_BY_ID_FAILED = "CAD_LITE_GET_MISSION_BY_ID_FAILED";

export const SAVE_MISSION = "CAD_LITE_SAVE_MISSION";
export const SAVE_MISSION_SUCCESS = "CAD_LITE_SAVE_MISSION_SUCCESS";
export const SAVE_MISSION_FAILED = "CAD_LITE_SAVE_MISSION_FAILED";

export const UPDATE_MISSION = "CAD_LITE_UPDATE_MISSION";
export const UPDATE_MISSION_SUCCESS = "CAD_LITE_UPDATE_MISSION_SUCCESS";
export const UPDATE_MISSION_FAILED = "CAD_LITE_UPDATE_MISSION_FAILED";

export const GET_ALL_MISSIONS = "CAD_LITE_GET_ALL_MISSIONS";
export const GET_ALL_MISSIONS_SUCCESS = "CAD_LITE_GET_ALL_MISSIONS_SUCCESS";
export const GET_ALL_MISSIONS_FAILED = "CAD_LITE_GET_ALL_MISSIONS_FAILED";

export const DELETE_MISSION = "CAD_LITE_DELETE_MISSION";
export const DELETE_MISSION_SUCCESS = "CAD_LITE_DELETE_MISSION_SUCCESS";
export const DELETE_MISSION_FAILED = "CAD_LITE_DELETE_MISSION_FAILED";
